name: Accessibility CI Gate

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  accessibility-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Start preview server
        run: |
          npm run preview &
          npx wait-on http://localhost:4173
      
      - name: Run Axe accessibility tests
        run: |
          npx @axe-core/cli http://localhost:4173 \
            --exit \
            --tags wcag2a,wcag2aa,wcag21a,wcag21aa \
            --chrome-options="--headless --disable-gpu --no-sandbox"
      
      - name: Run Pa11y CI tests
        run: npx pa11y-ci
      
      - name: Run component accessibility tests
        run: npm run test -- --run --reporter=verbose
      
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Accessibility tests passed! No WCAG violations detected.'
            })